### ISSUE TITLE
Drill loses track of progress when switching apps

### ISSUE THREAD

**Issue by gaul** [RodrigoDavy/Kana-Drill-Plus#14]
Start the drill activity and it will show a kana.  Switch apps and back and it will show a different kana.

**Comment by RodrigoDavy** [comment]
Most likely a lifecycle issue. It seems to happen in every other activity too. The app is vertical only from what it seems, this is usually a way to avoid losing track of progress when rotating the screen

This shouldn't be too hard to fix and I'll get to it eventually, but it may take a while. In case you wanna give it a try, I'll give it a try explaining the basics of how to fix this: (sorry if you already know this stuff)

First, a little information about how the Android lifecycle works: https://developer.android.com/guide/components/activities/activity-lifecycle

The proper way to fix that is saving all the necessary variables on savedInstanceState before the activity is stopped and reloading them when it's created again. There's an example of how I achieved this in another app of mine here: https://github.com/RodrigoDavy/PixelArtist/blob/master/app/src/main/java/rodrigodavy/com/github/pixelartist/ColorSelector.java (sorry for lack of comments, though). I save the variables state in the onSaveInstanceState() method and retrieve them in the onCreate() method. The solution for Kana Drill shouldn't be too different from this, you only need to know which variables should be stored and retrieved

Giving a look at the code, I noticed that every activity is actually forcefully finished and reopened on the onRestart method, by manually using the finish() method and then using an intent to start the same activity over again. I'm not sure why that's the case, since it wasn't me who wrote this code... In the MainActivity it says it has something to do with themes, but I'm afraid this might prevent us from using savedInstanceState to save our variables. We could workaround this by including those on the intent itself and writing the necessary code to handle it on onCreate, so the activity would retrieve the variables either from the intent or from the savedInstanceState
